#!/bin/bash

# fail fast
set -e

# debug
# set -x

BUILD_NO="${1:-`date +%Y%m%d-%H%M`}"

# apt-cache show r-base-dev | grep Version

./build_with_docker 3.2.5 "${BUILD_NO}" &> "build-3.2.5-${BUILD_NO}.log"
./build_with_docker 3.3.3 "${BUILD_NO}" &> "build-3.3.3-${BUILD_NO}.log"
./build_with_docker 3.4.4 "${BUILD_NO}" &> "build-3.4.4-${BUILD_NO}.log"
