#!/bin/bash

#
# use this script to build the R binaries on a heroku instance
#

#
# NOTE:
#
#  even though R is installed first via apt-get, it still needs to be built from
#  source, since the paths need to be in respect of /app/vendor for it to work.
#
#  also, by installing R with apt-get, any dependencies get installed, so we don't
#  have to build everything from source, as was the case in earlier versions of the buildpack.
#  E.g. the fortran77 compiler wasn't included in the cedar(-12) heroku stack
#

shopt -s extglob

# fail fast
set -e

# debug
# set -x

if [[ ! -f .env ]]; then
  cp .env.example .env
  echo "Please edit the .env file and supply your AWS credentials before continuing."
  exit 1
fi

r_version="${1:-3.2.1}"
stack="${2:-cedar-14}"
build_no="${3:-`date +%Y%m%d-%H%M`}"

# check arguments
if ([ -z "$r_version" ] || [ -z "$stack" ] || [ -z "$build_no" ]); then
  echo
  echo "USAGE: $0 VERSION [BUILDNUM]"
  echo
  echo "  VERSION    is the R version. E.g. 3.1.2"
  echo "  STACK      is the Heroku stack to build on. E.g. cedar-14"
  echo "  BUILDNUM   the build number. E.g. 20150301-4321"
  echo
  exit 1
fi

# create temporary working directory
# and copy files over...
dir=`mktemp -d`
cp -r . $dir

pushd $dir

rm -rf .git > /dev/null
git init
git add -f .buildpacks \
           .env \
           Aptfile \
           build-r \
           Gemfile \
           Gemfile.lock \
           s3_upload.rb \
           vars.mk

git commit -m "build scripts"

heroku apps:create --stack $stack --buildpack https://github.com/ddollar/heroku-buildpack-multi.git
app=`heroku apps:info -s | grep ^name=`
app=${app:5}

git push heroku master

sleep 10

# NOTE: Requires port 5000 to be open!
# See https://devcenter.heroku.com/articles/one-off-dynos#timeout-awaiting-process
heroku run "bash -c './build-r $r_version $build_no' &> ./build-r-$build_no.log; bundle exec ruby ./s3_upload.rb ./build-r-$build_no.log" --app $app

heroku apps:destroy $app --confirm $app

popd

# clean up temporary directory
rm -rf $dir

# download the file off s3
echo Downloading log file
wget "https://heroku-buildpack-r.s3.amazonaws.com/build-r-$build_no.log"

# echo Downloading binaries file
wget "https://heroku-buildpack-r.s3.amazonaws.com/R-$r_version-binaries-$build_no.tar.gz"
