#!/bin/bash

#
# use this script to build the R binaries with the `heroku/cedar:14` docker image locally
#

shopt -s extglob

# fail fast
set -e

# debug
# set -x

R_VERSION="${1:-3.3.2}"
BUILD_NO="${2:-`date +%Y%m%d-%H%M`}"
STACK="${3:-cedar-14}"
BUILDPACK_ARCHIVE="R-$R_VERSION-binaries-$BUILD_NO.tar.gz"

# build the buildpack
docker run -t \
  -v $(pwd):/var/tmp/scripts \
  --name "$R_VERSION-$BUILD_NO" \
  heroku/cedar:14 \
  /var/tmp/scripts/build_r $R_VERSION $BUILD_NO $STACK

# get the binaries archive
docker cp "$R_VERSION-$BUILD_NO:/app/R-$R_VERSION-binaries-$BUILD_NO.tar.gz" .

# upload to S3
aws s3 cp $BUILDPACK_ARCHIVE \
  "s3://heroku-buildpack-r/$STACK/$BUILDPACK_ARCHIVE" \
  --acl=public-read \
  --profile=heroku-buildpack-r
