#!/bin/bash

#
# use this script to build the R binaries with the heroku docker image locally
#

shopt -s extglob

# fail fast
set -e

# debug
# set -x

R_VERSION="$1"
BUILD_NO="${2:-`date +%Y%m%d-%H%M`}"

# check arguments
if ([ -z "$R_VERSION" ] || [ -z "$BUILD_NO" ]); then
  echo
  echo "USAGE: $0 VERSION [BUILD_NO]"
  echo
  echo "  R_VERSION      The R version to package."
  echo "                 E.g. 3.4.0"
  echo
  echo "  BUILD_NO       Optionally, the build number."
  echo "                 Defaults to todays date and current time, in the form \"YYYYMMDD-HHMM\"."
  echo
  exit 1
fi

STACK="heroku-16"
BUILDPACK_ARCHIVE="R-$R_VERSION-binaries-$BUILD_NO.tar.gz"
BUILDPACK_ARCHIVE_LATEST="R-$R_VERSION-binaries-latest.tar.gz"
TAG="vsv/heroku-buildpack-r-v$R_VERSION-$STACK:$BUILD_NO"

# for checking which version of the build script was used, output to STDOUT
# so that it gets included in the build log output file
echo "#======================================================================"
echo "# $0"
cat $0
echo "#======================================================================"
echo "# Dockerfile"
cat Dockerfile
echo "#======================================================================"
echo "# Environment"
set
echo "#======================================================================"

# build the image
docker build \
  --build-arg R_VERSION="$R_VERSION" \
  --build-arg BUILD_NO="$BUILD_NO" \
  --label "R_VERSION=$R_VERSION" \
  --label "BUILD_NO=$BUILD_NO" \
  --tag $TAG \
  .

# package up the binaries
docker run -t \
  -v $(pwd):/var/tmp/scripts \
  --name "$R_VERSION-$BUILD_NO-PKG" \
  "$TAG" \
  /var/tmp/scripts/package_r $R_VERSION $BUILD_NO $STACK

# get the binaries archive
docker cp "$R_VERSION-$BUILD_NO-PKG:/app/$BUILDPACK_ARCHIVE" .

# upload to S3
aws s3 cp $BUILDPACK_ARCHIVE \
  "s3://heroku-buildpack-r/$STACK/$BUILDPACK_ARCHIVE" \
  --acl=public-read \
  --profile=heroku-buildpack-r \
  --quiet

# clean up
docker rm "$R_VERSION-$BUILD_NO-PKG"

echo
echo "After testing the build, make it current by running the following:"
echo
echo " aws s3 cp s3://heroku-buildpack-r/$STACK/$BUILDPACK_ARCHIVE \\ "
echo "   s3://heroku-buildpack-r/$STACK/$BUILDPACK_ARCHIVE_LATEST \\ "
echo "   --acl=public-read \\ "
echo "   --profile=heroku-buildpack-r "
echo
