#!/bin/bash

function symlink_files() {

	# target $1 vs source $2
	echo "Comparing $1 -> $2"

	pushd "$1" > /dev/null

	for f in *
	do

		# directory?
		if [[ -d "$f" ]]; then

			# skip symlinked directories
			if [[ ! -L "$f" ]]; then
				symlink_files "$1/$f" "$2/$f"
			fi

		# regular file, which exists in source directory?
		elif [[ ! -L "$f" ]] && [[ -f "$2/$f" ]]; then

			# get file sizes
			i=$(wc -c "$f"    | cut -d' ' -f1)
			j=$(wc -c "$2/$f" | cut -d' ' -f1)

			if [ $i -eq $j ]; then
				echo "Linking $2/$f"
				ln -sf "$2/$f" "$f"
			fi

		fi

	done

	popd > /dev/null
}

symlink_files "$1" "$2"
